import { createRequestId, INnounceClientRequestEvent } from "../INnounceClientRequestEvent.ts";

/**
 * The `DesignLoadEvent` interface represents an event that is sent to load a design.
 *
 * Extends:
 * - `INnounceClientRequestEvent`: Specifies that this event conforms to the client request event
 *   structure and inherits its properties.
 */
export interface DesignLoadEvent extends INnounceClientRequestEvent {

}

/**
 * Creates and returns a new DesignLoadEvent object.
 *
 * The returned object includes a 'type' property set to "designLoadEvent"
 * and a unique 'requestId' generated by the createRequestId function.
 *
 * @return {DesignLoadEvent} A new DesignLoadEvent object containing event type and request ID.
 */
export function createDesignLoadEvent(): DesignLoadEvent{
	return {
		type: "designLoadEvent",
		requestId: createRequestId()
	}
}